theme = "catppuccin-macchiato"
padding-x = 2
padding-y = [0,0]
confirm-before-quit = false

[cursor]
shape = "block"
blinking = false

[editor]
program = "code"

[window]
width = 1100
height = 622
mode = "windowed"
windows-corner-preference = "RoundSmall"
decorations = "enabled"

[title]
content = "{{ title || program }}"
placeholder = "rio"

[renderer]
performance = "high"
backend = "Vulkan"
target-fps = 30
disable-occluded-render = true

[fonts]
size = 15
use-drawable-chars = true
disable-warnings-not-found = true
extras = [{ family = "Comic Code" }]
hinting = false

[fonts.regular]
family = "ComicCode Nerd Font"
style = "Normal"
width = "Normal"
weight = 500

[fonts.bold]
family = "ComicCode Nerd Font"
style = "Normal"
width = "Normal"
weight = 800

[fonts.italic]
family = "ComicCode Nerd Font"
style = "Italic"
width = "Normal"
weight = 500

[fonts.bold-italic]
family = "ComicCode Nerd Font"
style = "Italic"
width = "Normal"
weight = 800

[scroll]
multiplier = 4.0
divider = 1.0

[navigation]
mode = "Plain"
clickable = true
hide-if-single = true
current-working-directory = true
use-split = false

[shell]
program = "bash"

[bindings]
keys = [
	{ key = "v", with = "control", action = "none" },
	{ key = "w", with = "control", esc = "exit\r\n" },
	{ key = "q", with = "control", esc = "exit\r\n" },
	{ key = "n", with = "control", action = "CreateWindow" }
]

[platform]
windows.shell.program = "cmd"
